apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: testcron
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: testcron
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: nginx
            name: testcron
            command: ["/bin/bash", "-c"]
            args: ["/bin/date"]
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
status: {}
